apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: liatrio-demo
        image: chadd944/liatrio:latest
        # imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: liatrio-demo-api
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 5000
    targetPort: 5000
